fix Typescript any in main.ts file
michaljabi/js-na-frontach-zadania pull request #11
Opened 2022-09-22 17:47 UTC by gkubiak92

2022-09-23 19:37 UTC, michaljabi commented
@gkubiak92 , jest poprawnie ale na razie z zadania rozwiązany tylko 1 podpunkt :)

Brakuje:
> 2. Podziel projekt na kilka modułów.  
> 3. Uruchom projekt, aby sprawdzić poprawność działania

2022-09-23 19:38 UTC, michaljabi requested changes
@gkubiak92 , jest poprawnie ale na razie z zadania rozwiązany tylko 1 podpunkt :)

Brakuje:
> 2. Podziel projekt na kilka modułów.  
> 3. Uruchom projekt, aby sprawdzić poprawność działania

2022-09-24 13:54 UTC, gkubiak92 commented
@michaljabi dodałem rozwiązania do zad 2 i 3, co sądzisz?

2022-10-12 20:22 UTC, michaljabi requested changes

2022-10-12 20:22 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/main.ts
>  const isAdult = hasGivenAge(18)
detal: to bym jeszcze dodał do `userValidators` @gkubiak92 - a tak to git jest :)

2022-10-30 07:25 UTC, closed without merging