Solutions/week2/e02
michaljabi/js-na-frontach-zadania pull request #115
Opened 2022-10-11 18:39 UTC by kdrzymalski

2022-10-13 16:03 UTC, kdrzymalski commented
Uruchom server poleceniem:
json-server --watch db.json

2022-11-03 09:52 UTC, michaljabi requested changes
Jest dobrze - ale jest `challenge` - szczegóły niżej :)

2022-11-03 09:52 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/package.json
> +    "build": "vite build"
To polecenie powinno być tutaj @kdrzymalski :)
np.
```json
"start:backend": "json-server --watch db.json"
```

Właśnie między innymi po to są `"scripts"`

2022-11-03 09:52 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/order.service.js
> +}
bardzo ładnie przygotowana fasada do rozdania orderów.

2022-11-03 09:52 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/api/getOrders.ts
> +}
Mam dla Ciebie `challenge` - zmień proszę to API i zastosuj `ajax` ale z `RxJS` 

zobacz:
https://www.learnrxjs.io/learn-rxjs/operators/creation/ajax

wtedy połącz strumień z `ajax` z tym co masz w `OrdersService`

Albo zastosuj podejście rodem z `Angular` i zrób osobny AjaxService (HttpService)

2022-11-03 09:52 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/order.service.js
> +}
przygotowane wszystko pod dalszą implementację :) jest spoko

2022-11-27 04:44 UTC, closed without merging