Code Review "solutions/week1/e01"
michaljabi/js-na-frontach-zadania pull request #12
Opened 2022-09-22 20:59 UTC by janossik

2022-09-22 21:01 UTC, janossik commented
Chciałem ustawić "Reviewers", ale z jakiegoś powodu nie mogę ;<

2022-09-23 08:09 UTC, michaljabi requested changes
Generalnie jest spoko :)

Tylko pomyślałbym na bardziej zdradzającymi co się dzieje dookoła - nazwami katalogów.
Nie jestem też zwolennikiem tworzenia `barrel` modułów jako `index.ts`.

2022-09-23 08:09 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/package.json
> +    "start": "rm -rf dist && tsc ./src/main.ts --noImplicitAny --removeComments --outDir dist && node dist/main.js"
Fajnie że sobie łączysz komendy w ten sposób, ale polecam Ci rozbić ten pieline na osobne skrypty
i mieć właśnie taki jeden:
"build" który je ze sobą łączy tak jak masz teraz.

Troszkę elastyczniejsze podejście wtedy.

Zobacz sobie też narzędzie `ts-node` + `nodemon` jeśli nie znasz / nie kojarzysz, a może znasz tylko `nodemon`.

Wtedy ustawić sobie możesz skrypt `"dev":"...."` z wykorzystaniem tych narzędzi

2022-09-23 08:09 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/utils/index.ts
> +};
Nie ma potrzeby "nadużywania" arrow function :) na spokojnie mogą to być zwykłe funkcje.

Być może jakbyś miał tego tonę tutaj - to wtedy ten zapis by coś poprawił. Choć wtedy byśmy to rozbijali pewnie na inne pliki :)

2022-09-23 08:09 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/utils/index.ts
> +};
Utils to nazwa bardzo generyczna - może: `user.validators` ? i tutaj też dać `isAdult` ?

2022-09-23 08:09 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/types/index.ts
> +}
Te interface'y fajnie by było przedstawić jako osobne pliki żebyśmy znali model danych

Tutaj reprezentują raczej `model` jako np. `model/Adress.ts` czy `model/User.ts`

2022-09-23 08:41 UTC, janossik commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/utils/index.ts
> +};
Hymm muszę się zgodzić, że nie było potrzeby używania arrow function" ale też nie wiem czy to jest "nadużywanie". Ostatecznie to prawda nie było powodu, żeby to nadpisywać ;)

2022-10-12 20:23 UTC, michaljabi approved these changes
super 👍

2022-10-12 20:23 UTC, closed without merging