Solutions/week2/e02
michaljabi/js-na-frontach-zadania pull request #131
Opened 2022-10-16 23:28 UTC by adamJacewicz

2022-11-03 08:57 UTC, michaljabi requested changes
Uwaga ogólna:

- trochę dużo arrow functions :D 
- w `helperach` to jeszcze ujdzie - rozumiem
- ale w np,. komponentach czy `init` - to mogą byc zwykłe `functions`

nie jest to błąd oczywiście, ale generalnie `arrow` jest tam gdzie `callbacks` oraz tam gdzie nie da się inaczej + ew. helpers (one-liners)

natomiast tu i tam w kodzie czasem warto skorzystać ze zjawiska hoistingu funkcji - tam gdzie to bezpieczne.
no i z zapisu `function` dla samej wizualnej organizacji kodu.

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +export class Orders {
bardzo ładnie zafasadowana logika dla `Orders` razem ze strumieniami.

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +    return this.#source.pipe(map(getBestSale));
pamiętaj że to można było już zrobić w polu klasy np:
```typescript
#bestSales = this.#source.pipe(map(getBestSale));
```
a potem tutaj:

```typescript
getBestSale(): Observable<number> {
  return this.#bestSales;
}
```

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +    return this.#source.asObservable();
Nie rozumiem dlaczego tutaj `Promise` zwracasz. można by było normalnie `Observable<OderType[]>`

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +    return this.#source.asObservable();
Dodatkowo nie potrzebujesz czegoś takiego jak `wait(1000)`
RxJs sam sobie poradzi z takimi tematami, zobacz `timer` oraz `switchMap`
https://www.learnrxjs.io/learn-rxjs/operators/creation/timer

https://www.learnrxjs.io/learn-rxjs/operators/transformation/switchmap

```typescript
getAllOrders(): Observable<OrderType[]> {
    return timer(1000).pipe(switchMap(() => this.#source))
}
```

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +  }
tak samo:
```typescript
timer(1000).subscribe(() => {
 const newOrder = createOrder(
      sale,
      `${this.#source.value.length}/${new Date().getFullYear()}`
    );
    this.#source.next([...this.#source.value, newOrder]);
})
```

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/helpers.ts
> +  );
fajny generator

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +    return this.#source.pipe(map(getTotalIncome));
bardzo ładnie zrealizowany temat `helpers` gdzie pozamykałeś @adamJacewicz te funkcyjki sobie i mają swoje miejsce.

Ja bym jedynie dał inną nazwe na ich mieszkanie `helpers.ts` to dla mnie zbyt "generyczna" nazwa. nie mówiąca zbyt wiele.

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/main.ts
> +};
To rozwiązanie najmniej mi się podoba z całego kodu (reszta koncepcyjnie jest bardzo w porządku, fajowo że korzystasz z `RxJS` i wiesz jak sobie `Ramde` wpiąć we własne funkcje i zastosować kompozycję.

Tutaj `init` robi za dużo.
Powinien zainicjować każdy komponent ale dać mu pełny `ordersStore`
i wtedy każdy komponent SAM zdecyduje do jakiego strumienia ordersStore się wpina i subskrybuje zmiany.

Tutaj `init` podejmuje niepotrzebnie za dużo decycji o tym kto co dostanie.
Komponent sam sobie to powinien "ogarniać"

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/model/orders.ts
> +export type OrderType = {
To bym dał do osobnego pliku w tym folderze.

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/helpers.ts
> +export const getTotalIncome = (list) => compose(sum, getSales)(list);
tutaj te parametry `list` są implicit `:any`

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/tiles/AnnualOrdersTile.ts
> +  const panel = mountPoint?.querySelector("[data-panel]");
te `const` mogą byc poza tą funkcją.

2022-11-03 08:57 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/tiles/AddOrderButton.ts
> +  const button = document.querySelector('[data-button="add-order"]');
selektor daj poza funkcją. będzie wydajniej.

2022-11-07 12:03 UTC, adamJacewicz commented
> Uwaga ogólna:
> 
> * trochę dużo arrow functions :D
> * w `helperach` to jeszcze ujdzie - rozumiem
> * ale w np,. komponentach czy `init` - to mogą byc zwykłe `functions`
> 
> nie jest to błąd oczywiście, ale generalnie `arrow` jest tam gdzie `callbacks` oraz tam gdzie nie da się inaczej + ew. helpers (one-liners)
> 
> natomiast tu i tam w kodzie czasem warto skorzystać ze zjawiska hoistingu funkcji - tam gdzie to bezpieczne. no i z zapisu `function` dla samej wizualnej organizacji kodu.
> 
> Super że użyłeś `RxJS` ! generalnie fajnie to wyszło.


Dzięki za wskazówki, kod poprawiony + zrobiłem mały refactor

2022-11-27 05:34 UTC, michaljabi approved these changes
Bardzo ładne poprawki - brawo 🥇

2022-11-27 05:35 UTC, closed without merging