Solutions/week5/e01 to review
michaljabi/js-na-frontach-zadania pull request #137
Opened 2022-10-19 17:06 UTC by teziovsky

2022-11-04 13:36 UTC, michaljabi requested changes
`"build"` ślicznie

`"dev"` do poprawki (u mnie nie działa tak jak bym chciał)

2022-11-04 13:36 UTC, michaljabi commented on .gitignore
> +dist
`dist` i tak się wysłał na repo :)

2022-11-04 13:36 UTC, michaljabi commented on week-5-ci-and-production/w05e01-npm-pipeline/package.json
> +    "dev": "npm run copy-index && npm run transpile -- --watch & npm run bundle -- --watch & npm run serve -- --watch"
"build" jest ślicznie zrobiony natomiast:

> "dev"

To tak:
`serve` nie potrzebuje `--watch`

Więc powinno być:
`nom run serve` tylko

I teraz jak uruchamiam od Ciebie `npm run dev` to nie widzę serwera dev na porcie 8200. Nie działa.

Jeśli zmienię znaczki `&` na `|` - pojedyncze - to działa ok.

Tylko - tam jest taki błąd "nie do pozbycia się" chyba, że pierwsze uruchomienie zwróci błąd bo nie ma jeszcze `dist/main.js` jak bundler chce zrobić bundle.

Co równa się temu, że trzeba `dev` zrestartować po pierwszym użyciu.

Chyba że zamiast takiego pipeline:
```json
"dev": "npm run copy-index && npm run transpile -- --watch | npm run bundle -- --watch | npm run serve"
```

zrobimy workaround taki:
```json
"dev": "npm run copy-index && npm run transpile && npm run transpile -- --watch | npm run bundle -- --watch | npm run serve"
```

Wtedy 1wszy tranpsile jest po to żeby był obceny `dist/main.js` a drugi jest w "watch mode" - więc nigdy się nie kończy, więc mamy `dev` setup ustawiony.

i to się sprawdza.

Daję Ci rozwiązanie "na tacy" - bo widzę że wiesz o co chodzi i tutaj ładnie sobie to ogarnąłeś :) 
Sprawdź jednak czy u Ciebie @teziovsky działa i ew. popraw tutaj w kodzie :)

Pamiętaj żeby zawsze kasować `/dist`, żeby być na `100`% pewnym że to działa jak powinno

2022-11-06 17:38 UTC, teziovsky commented on week-5-ci-and-production/w05e01-npm-pipeline/package.json
> +    "dev": "npm run copy-index && npm run transpile -- --watch & npm run bundle -- --watch & npm run serve -- --watch"
Wyrzuciłem dist z githuba – nie wiem jakim cudem on się tutaj wkradł, skoro był w gitignorze. No i zaktualizowałem skrypt `dev` 🎉

Jak będzie git to możesz zamknąć 😎

2022-12-14 17:34 UTC, michaljabi approved these changes

2022-12-14 17:34 UTC, closed without merging