`Solutions/week1/e01`
michaljabi/js-na-frontach-zadania pull request #16
Opened 2022-09-23 20:14 UTC by noszczynski

![CleanShot 2022-09-23 at 22 12 41@2x](https://user-images.githubusercontent.com/50596437/192049451-35321bd3-6f88-4040-95b1-2f560b54b715.png)

2022-09-26 13:38 UTC, michaljabi requested changes
Szczegóły i komentarze przy kodzie w plikach :)

2022-09-26 13:38 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/package.json
> +    "start": "ts-node src/main.ts"
Warto dorzucić sobie `nodemon` będzie działał "out of the box" z `ts-node` a szybciej sobie będziesz pisał kodzik w oparciu o tzw. "watch mode"

2022-09-26 13:38 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/types/User.ts
> +export interface UserAddress {
Ten interface nie jest nigdzie wykorzystywany - może warto go na razie trzymać schowanego tutaj.

2022-09-26 13:38 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/tsconfig.json
> +    "outDir": "dist",
Fajnie że masz wydzielony build do osobnego katalogu 👍

2022-09-26 13:38 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/types/User.ts
> +}
Sam katalog przy tym podziale nazwałbym `model` zamiast `types` :)

Zobacz że `User` to kształt Twoich danych ale w aplikacji spełnia rolę modelową.

2022-09-26 13:38 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/main.ts
> +const isAdult = hasGivenAge(1)
tutaj przy refactoringu do TS coś sie logika zmieniła bo jest `hasGivenAge(1)` zamiast `(18)`

2022-09-26 18:00 UTC, noszczynski commented on week-1-ts-ecosystem/w01e01-typescript-basics/tsconfig.json
> +    "outDir": "dist",
Dzięki!

2022-09-26 18:01 UTC, noszczynski commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/types/User.ts
> +}
częściowo się zgadzam. ustawię `models`

2022-09-26 18:01 UTC, noszczynski commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/main.ts
> +const isAdult = hasGivenAge(1)
jakiś chochlik się wkradł, dzięki!

2022-10-12 21:14 UTC, michaljabi approved these changes
spoko 🏅 @noszczynski

2022-10-12 21:14 UTC, closed without merging