solutions/week1/e02
michaljabi/js-na-frontach-zadania pull request #17
Opened 2022-09-23 21:46 UTC by janossik

W tym zadaniu zdecydowałem się wykorzystać **vite** dla rozwiązania podpunktu: _"konieczność nieustannego uruchamiania i testowania w celu sprawdzenia, czy nie ma literówek"_ (mam nadzieje, że o takie coś chodziło). Co do literówek to warto byłoby zdefiniować więcej enumów (lub obiektów) posiadające zdefiniowane wartości jak `CURRENCY`.

_"Konieczność częstego biegania po dokumentacji MDN w kontekście korzystania z `DOM` w **JS**"_ myślę, że dostosowanie `createElement` z `dom-creators.ts`, na przyjmowanie typu generycznie rozwiązuje ten problem.

2022-09-23 21:48 UTC, janossik commented
Niestety nie mogę sam ustawić 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/62254945/192061181-73eecc63-b0cc-4e86-819c-b2c99edb01dc.png">

2022-09-26 14:08 UTC, michaljabi requested changes
Tak jest _vite_ to jeden z bundlerów, którego można użyć w projekcie.
O coś takiego chodziło.

Jednak nie widze migracji do `ts` - krok po kroku :) 
Polecam - to ciekawe doświadczenie.

Dodatkowe komentarze moje przy kodzie plików.

2022-09-26 14:08 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/Price.type.ts
> +  currency: CURRENCY;
Całkiem spoko, zauważ że na 1 ogień sam typ `"PLN"` a potem ew. unia : `"PLN" | "EUR"` etc... jakby weszły kolejne waluty  - robiłby robotę.

2022-09-26 14:08 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/Hero.type.ts
> +}
Proponowałbym inny podział.

Zauważ, że mamy tylko 1 typy odpowiedzialne za naszą "logikę biznesową" albo inaczej "Dane biznesowe" w naszej aplikacji jest nim `Card`

troszkę nie wiem skąd ta nazwa u Ciebie, bo bardziej pasuje tutaj po prostu `Item` w sensie:
cart-item jest jako `Cart` od "koszyk" z "t" na końcu.

W każdym razie. jeśli założysz że pokażesz interfejs u Ciebie: `Card` to pozostałe elementy stąd, mogą być
inlinenowo lub per "component" schowane w środku.
I tak jako "prop-types" będą pilnowały poprawności a nie będziemy ich musieli zawsze wrzucać tutaj jeśli cokolwiek nowego przyszykujemy z komponentów.

Zobacz, w tym układzie za każdym razem jak dodam nowy koponent w aplikacji to muszę przybiec tutaj do `types` i dodać jego `prop-type` żeby sie zgadzało.
To uciążliwe i prawdopodobnie potrzebne tylko jeden raz, bo nigdzie więcej nie wykorzystam tego typu.

Zamiast podawać tutaj `Hero` czy `CartPanel` zostawiłbym je zamknięte w plikach z tymi komponentami.

Co do nazw:

`*.type.ts`

Wydaje mi się że z jednej strony "pomagają" bo wyraźnie zaznaczają że coś ma charakter tylko typu,
jednak z 2 storny jeśli masz faktycznie tylko typy i nie chcesz ich "mieszać" z kodem to TS ma do tego 
odpowiednie pliki: `*.d.ts` i tutaj można by było ich użyć

2022-09-26 14:08 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/utils/currency.utils.ts
> +}
Ten `enum` powiązany jest z modelem danych więc to nie do końca `util`

2022-09-26 14:08 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/framework/dom-creators.ts
> +  return element as TypeElement;
Ten typ generyczny nie jest do końca zrobiony na `100%` pewnie.
Owszem dobrze że można go wybrać jedynie z `HTMLElement` jednak tutaj jest asercja typu,
co oznacza że wpis w Twoim kodzie w stylu:
```
... createElement<HTMLDivEelement>('p', className);
```
Też będzie poprawny (sprawdź)

co nie jest do końca prawdą.

Jeśli jako typ generyczny zastosujesz z kolei unię tych elementów, które wybiera framework:
`<TypeElement extends 'p' | 'div' | 'article' | 'section'>(tagName: TypeElement .... `

wtedy bez asercji typów `as TypeElement `

i bez konieczności podawania:
```
createElement<HTMLParagraphElement>('p', className);
```
wystarczy samo:
```
createElement('p', className);
```
 a TypeScript wywnioskuje że to: `HTMLParagraphElement`

2022-09-26 18:43 UTC, janossik commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/utils/currency.utils.ts
> +}
więc gdzie najlepiej umieścić takiego enum-a?

2022-09-26 19:04 UTC, janossik commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/Hero.type.ts
> +}
plik: `*.d.ts` umieszczam w jakimś folderze types czy w tym samym folderze co kod?

2022-12-14 16:37 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/Hero.type.ts
> +}
Jeśli stosujesz podział `types` jako folder - to mogą być tutaj. jeśli będziesz dzielił aplikację "feature like" że dany folder będzie grupował powiązane elementy - to wtedy pliki z typami mogą mieszkać w zależności od tego co grupujesz - razem z tym feature'em.

Przykładowo:
```
user 
  | - user.service.ts
  | - user.interface.ts
  | - user-list.component.ts
```

to podział "feature like" = wszystko co dotyczy obszaru "user" jest trzymane w jednym miejscu.

2022-12-14 16:37 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/utils/currency.utils.ts
> +}
Jeśli masz `types` - jako osobny folder - to tam. Jeśli nie, to tam gdzie zrobisz podział wspomniany wyżej "fatrure like" - wtedy to z czym jest związane `CURRENCY` będzie wyznaczało gdzie je wrzucić

2022-12-14 16:37 UTC, closed without merging