solutions week1 eo2
michaljabi/js-na-frontach-zadania pull request #25
Opened 2022-09-24 22:30 UTC by kdrzymalski

2022-09-28 13:33 UTC, michaljabi requested changes
Generalnie całość bez zarzutu
jedyne co to typowanie `HTMLElement` bym poprawił w kilku miejscach

a tak to jest super.

Brakuje mi tego co u pozostałych - cała ta migracja jest robiona u Ciebie na jednym `commit`cie
jak na jednym wydechu :)
Mam nadzieję że krokowo sobie podszedłeś do tematu migracji do TS.

2022-09-28 13:33 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/item.ts
> +  currency: 'PLN' | 'USD' | 'EUR'; // TODO check required currencies
Fajny pomysł z `currency` jako `union` - prosty i skuteczny 👍

2022-09-28 13:33 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/types/item.ts
> +export interface Item {
Ja proponuje Ci to nazwać jako `models/` zamiast `types/` a tak to jest super.

Model będzie podbijał ważność kształtu tych danych pod względem samej "logiki działania koszyka". 
To takie pokazanie faktu "zobaczcie operujemy na `Items`".

2022-09-28 13:33 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/shop/cart-item.component.ts
> +export function cartItem({ name, amount, unit, price }: Item): HTMLElement {
Tutaj pamiętaj że możesz być bardziej "specyficzny" To co jest zwracane to dokładnie `HTMLDivElement` który owszem - dziedziczy po `HTMLElement` - dlatego `TypeScript`'owi to pasuje

2022-09-28 13:33 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/shop/cart-item-sum.component.ts
> +export function cartItemSum({ value, currency = 'PLN' }: Price): HTMLElement {
Tutaj pamiętaj że możesz być bardziej "specyficzny" To co jest zwracane to dokładnie `HTMLDivElement` który owszem - dziedziczy po `HTMLElement` - dlatego `TypeScript`'owi to pasuje

2022-09-28 13:33 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/framework/dom-creators.ts
> +function createElement(tagName = 'div', className = ''): HTMLElement {
Ten `:HTMLElement` nas tutaj troszkę ogranicza bo to nie zawsze będzie to - będzie to zależne od `tagName` co zostanie przygotowane.

2022-09-29 21:15 UTC, kdrzymalski commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/framework/dom-creators.ts
> +function createElement(tagName = 'div', className = ''): HTMLElement {
Jest jakiś dobry sposób żeby to otypować inaczej niż Unią?

2022-10-12 20:45 UTC, michaljabi requested changes

2022-10-12 20:45 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/shop/cart-item-sum.component.ts
> +  return $panelBlock as HTMLDivElement;
ta asercja typów nie powinna tutaj być potrzebna `as` jeśli TS na Tobie @kdrzymalski ją wymusza, to oznacza że coś można ulepszyć w `dom-creators.ts`

2022-10-12 20:45 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/framework/dom-creators.ts
> +function createElement(tagName = 'div', className = ''): HTMLDivElement | HTMLParagraphElement | HTMLElement {
jeśli Twój `tagName` będzie typem generycznym - to poprawisz typowanie i wnioskowanie TS

2022-11-27 05:18 UTC, michaljabi requested changes

2022-11-27 05:18 UTC, michaljabi commented on week-1-ts-ecosystem/w01e02-enter-the-world-of-typescript/src/framework/dom-creators.ts
> +  const element = <T>document.createElement(tagName);
Dalej tego nie kupuje xD `asercja typów` to jest dalej tylko z drugiej strony (inny syntax niż `as`)

2022-11-27 14:22 UTC, closed without merging