Solutions/week1/e03
michaljabi/js-na-frontach-zadania pull request #26
Opened 2022-09-25 11:23 UTC by gkubiak92

2022-09-30 07:46 UTC, michaljabi requested changes
Z punktu widzenia samej logiki działania - jest bardzo poprawnie.

Zrefaktoryzowałbym tylko `class + interface` i przeszedł na same klasy.
Gdzie odkryjesz używane modele danych 

Przykładowo:

`BuyNowItem` `AuctionItem` `FreeItem`

wszystkie dziedziczące po bazwym: `BaseItem` 

Coś w ten deseń, żeby nie musieć trzymać jednocześnie i interface i class - robiących to samo.

2022-09-30 07:46 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/cart/cart.ts
> +export class Cart<Type extends ProductType> {
Samo wykorzystanie tutaj generyków - to dobra droga. Jednak istnienie `ProductType` razem z `Product` spowodowało że Twój kształt danych @gkubiak92 jest "rozproszony" w 2 miejscach

i tak naprawdę i `class` i `interface` robią to samo - pilnują tego samego modelu danych.
W tym układzie jeśli coś byś chciał zmienić w modelu - musisz to zrobić w 2 miejscach.

Zauważ że klasa to reprezentacja za równo danych jak i typu danych.
Powienieneś przejść na np. układ klas z Konretnymi nazwami typów produktu dziedziczącymi po klasie bazowej.

2022-09-30 07:46 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/cart/cart.ts
> +  updateProduct(id: string, updatedProduct: Partial<Omit<Product<Type>, "id">>) {
Fajnie że kojarzysz takie "wytrychy" jak `Omit` :)

2022-09-30 07:46 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/cart/cart.ts
> +      return this.updateProduct(existingProduct.id, {quantity: existingProduct.quantity + product.quantity})
Fajnie uchwycony temat zwiększenia ilości elementów o tym samym id produktowym z `quantity`

2022-10-02 14:35 UTC, gkubiak92 commented
Dzięki za tipi, wprowadziłem poprawki, mam nadzieję, że teraz to wygląda już lepiej

2022-10-12 20:57 UTC, michaljabi requested changes
Generalnie bardzo spoko. 🏅 

Zobacz jeszcze moje komentarze @gkubiak92 
i zdecyduj co dalej

2022-10-12 20:57 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/product/product.ts
> +  type: ProductType;
tutaj możesz dać słowo kluczowe `abstract`

wtedy wymusisz na każdej klasie, która dziedziczy po `BaseProduct` 
implementację tego pola.

Jednocześnie będziesz je mógł wywalić z konstruktorów - bo nie mają tam i tak racji bytu.

2022-10-12 20:57 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/product/product.ts
> +  type: ProductType;
```typescript
abstract type: ProductType;
```

2022-10-12 20:57 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/product/product.ts
> +  type: ProductType = "FREE";
Generalnie jeśli krytycznie popatrzysz na to rozwiązanie, to okazuje się że `type` nam bardziej przeszkadza niż pomaga. W sensie - to teraz infromacja nadmiarowa, ponieważ klasa "świadczy sama o sobie"

No i wiem co powiesz... 
> Ale Jabi.... przecież skądś musimy wiedzieć że ten typ to ten typ

No ... zgadza się - ale od czego mamy `instanceof` ?

```typescript
const item = new FreeProduct(/*....*/)

console.log(item instanceof BaseProduct) // true
// ok to jest product

console.log(item instanceof FreeProduct) // true
// ok to jest FreeProduct
```

2022-10-12 20:57 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/cart/cart.ts
> +export class Cart<Product extends BaseProduct> {
Drobny detal, Wartości generyków pisz z dużej litery.

Taka konwencja.
Czyli tutaj będzie:

```typescript
export class Cart<PRODUCT extends BaseProduct> { }
```

wtedy łatwo w kodzie wychwycić gdzie jest generyk.
Bardzo często spotkasz się z tym że w generykach te "zmienne" są podawane jako jedna litera np. `P`.

2022-11-27 04:30 UTC, closed without merging