Review me
michaljabi/js-na-frontach-zadania pull request #30
Opened 2022-09-25 15:51 UTC by zawadzki-dawid

2022-09-30 08:03 UTC, michaljabi approved these changes
Jest bardzo ładnie @zawadzki-dawid , jedyne co mi nie tyle "nie pasowało" co chciałbym zebyś wybronił "po co ?" - bo mnie ciekawi to :)

Dodatkowo możesz poprawki dosłać jeśli chcesz bo znalazłem tam (pewnie wynikający z przypadku) brak konsekwencji w jednym momencie.
Sprawdź sobie na spokojnie.

2022-09-30 08:03 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Products.ts
> +export abstract class Product {
Super tutaj zauważyłeś że `Product` może być abstrakcyjny - żeby na jego bazie budować konkretne modele danych.

2022-09-30 08:03 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Purchase.ts
> +export class Purchasable implements Purchase {
Osobiście uważam że ta klasa to już "za dużo" :) 

W sensie już w samych konstrukturach poszczególnych klas - mogłeś osbługiwać tę logikę.
Może ja tutaj czegoś nie dostrzegam, albo jesteś @zawadzki-dawid o jeden krok dalej z "wyobrażeniem"
jak to będzie się rozwijało :) i tutaj się przygotowałeś na obsługę tego.

2022-09-30 08:03 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Cart.ts
> +        })
W mojej opinii to mapowanie nie jest tutaj potrzebne.
Rozumiem "nie mutowanie" danych - ale nie mamy tutaj React'a :)

Można swobodnie skorzystać z referencji do znalezionego obiektu


jeśli chcesz już pozostać przy tym zapisie, to masz tutaj lukratywną sytuację do użycia `conditional operator`'a
Bo za równo `if `jak i poza `if` masz `return` :)

2022-09-30 08:03 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Cart.ts
> +        this.products.push(product)
Aaaa widzisz i tutaj bym Ci zarzucił brak konsekwencji :) Bo `updateProduct` nie mutuje - a tutaj mutujesz.

(ps - jak zobaczysz na dole, ja bym mutował)

2022-09-30 08:03 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Cart.ts
> +    }
Tutaj też bardzo ładnie to wygląda że `fullPrice` jest u Ciebie `computed` za każdym razem gdy ktoś o nią pyta.
Fajnie.

2022-10-02 19:41 UTC, zawadzki-dawid commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Cart.ts
> +        })
Masz rację, niepotrzebny zabieg :)

2022-10-02 19:59 UTC, zawadzki-dawid commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Purchase.ts
> +export class Purchasable implements Purchase {
Hmm, już teraz nie jestem przekonany czy to nie jest `Overengineering` :D Ostatnio zacząłem się uczyć wzorców projektowych i możliwe, że jeszcze nie umiem ich dobrze używać. Mój tok myślenia był taki, że skoro są różnego typu produkty (w przyszłości może być ich więcej) to warto zapewnić klasy, które pozwolą na ponowne użycie kodu, dla produktów, które mają mieć taki sam typ `purchase`. Akurat w tym przypadku te klasy dużo nie wnoszą, bo to tylko zwykły `getter` ceny i raczej ciężko sobie wyobrazić przypadek, kiedy będzie potrzeba dodania innej funkcjonalności niż `Purchasable` i `NonPurchasable`, dlatego prawdopodobnie jest to niepotrzebne :D

2022-10-12 20:39 UTC, michaljabi requested changes
Taki detal jeszcze złapałem przy 2-gim kołowaniu ✈️

2022-10-12 20:39 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/Cart.ts
> +        const index = this.products.findIndex(product => product.id === id)
Ten fragment logiki powtarza Ci się w 2 miejscach, może warto to zrobić jako `private` wrzucić metodę 

`const index = this.getProductIndex(id)`

zwracać `index` i wykorzystać go w `removeProduct` , `updateProduct` oraz `getProduct`

2022-10-30 07:26 UTC, closed without merging