Solution W01 E01
michaljabi/js-na-frontach-zadania pull request #4
Opened 2022-09-21 20:52 UTC by pawlako93

2022-09-22 00:26 UTC, michaljabi requested changes
Drobne poprawki w nazewnictwie plików (do przemyślenia) - a tak to - bez zarzutu. 
O to chodziło - brawo.

2022-09-22 00:26 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/utils.ts
> +export const isAdult = hasGivenAge(18);
Ten plik nazwałbym inaczej 

`utils.ts` jest zbyt ogólne.
Jeśli bardzo chcesz iść w te strone to: `user-utils.ts`

a lepiej moim zdaniem np.:
`user.validators.ts`

2022-09-22 00:26 UTC, michaljabi commented on week-1-ts-ecosystem/w01e01-typescript-basics/src/types.ts
> +}
To `types.ts` to też dość "uogólniona nazwa".

Co powiesz na `user.model.ts`

podoba mi się że zauważasz tutaj 2 typy i rozdzielasz `Address` i `User`
oraz na razie nie udostępniasz `Address` bo nie ma takiej konieczności - cool.

2022-09-25 10:08 UTC, pawlako93 commented
Hej, zmieniłem nazwy plików na bardziej czytelne :)

2022-09-26 11:32 UTC, michaljabi approved these changes
Super. wygląda dobrze, dzięki za poprawki

2022-09-28 09:17 UTC, closed without merging