Solution for exercise 4
michaljabi/js-na-frontach-zadania pull request #46
Opened 2022-09-26 16:57 UTC by NiestrojMateusz

2022-09-30 18:04 UTC, michaljabi requested changes
Dałem znaka poniżej co do poprawki :)

2022-09-30 18:04 UTC, michaljabi commented on week-1-ts-ecosystem/w01e04-light-me-up/src/LightBulb.ts
> +  lightUpFor(seconds) {
Tutaj brakuje fizycznego upływu czasu :) co sekunda - to ma faktycznie tak swiecić.

Dodatkowo seconds nie ma typu (implicit `any`).

Ale nie musi tego w ogóle być.
ZObacz - wkręcasz żarówkę - i ona ma świecić. Ona będzie świecić tylko `5` sekund bo tylko tyle jest mocy w `powerSource`
Wiec nie powinieneś ustalać ile ma to świecić tylko obsłużyć błąd jak świecić przestanie.

2022-09-30 18:04 UTC, michaljabi commented on week-1-ts-ecosystem/w01e04-light-me-up/src/ex1.ts
> +lightBulb6.lightUp();
Brakuje obsługi błędu `try... catch`

2022-09-30 18:04 UTC, michaljabi commented on week-1-ts-ecosystem/w01e04-light-me-up/src/PowerSource.ts
> +    }
Jakbyś odwrócił warunek to uprościłoby zapis @NiestrojMateusz dlatego że wtedy `throw` przerwie i tak działanie metody.

2022-10-01 04:57 UTC, michaljabi commented on week-1-ts-ecosystem/w01e04-light-me-up/src/LightBulb.ts
> +  lightUpFor(seconds) {
Tutaj mój błąd - to że ma to świeci `n` sekund - wynikało z treści zadania - więc może tak zostać :)

2022-10-02 06:38 UTC, michaljabi commented
@NiestrojMateusz 
https://community.ahoy.so/c/zadania/ukryte-znaczenie-zadania-w01e04-zarowka

2022-10-02 12:36 UTC, NiestrojMateusz commented
Dzięki za uwagi. Dodałem poprawki i obsługę błędów

2022-10-12 22:47 UTC, michaljabi approved these changes
Daje jeszcze każdemu z tego zadania do poczytania:

https://nodejs.org/docs/latest-v16.x/api/process.html#process_event_uncaughtexception

2022-10-12 22:47 UTC, michaljabi commented on week-1-ts-ecosystem/w01e04-light-me-up/src/LightBulb.ts
> +  lightUpFor(seconds: number, onError?: (e: Error) => void) {
Bardzo fajnie @NiestrojMateusz 

Zastosowałeś jeden z 2 sposobów rozwiązania tego problemu - `callback`.
Drugim jest zapakowanie tego w `Promise` czyli mikrotask.

Jeśli chcesz możesz pokombinować z rozwiązaniem `promisified` 🎓 
Ale to jest jak najbardziej - ok.

2022-11-27 04:48 UTC, closed without merging