Solutions/week1/e03
michaljabi/js-na-frontach-zadania pull request #53
Opened 2022-09-28 06:55 UTC by kdrzymalski

2022-10-08 02:13 UTC, michaljabi requested changes
Jest to dobrze wykonane zadanie bez użycia generyka :)

Jednak masz nadmiarową logikę jeśli chodzi o `interfaces` nie są one potrzebne do szczęścia i stwarzają dodatkowe "koszty" (potrzeby ich synchronizowania z API samej klasy).

Więcej szczegółów w komentarzach do plików.

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/cart.ts
> +    } else {
`else` niepotrzebny bo i tak jeśli się nie wykona `if` to tutaj trafimy a `throw` przerwie działanie funkcji

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/cart.ts
> +    this.products = this.products.map((product) => {
produkt może być updateowany przez referencję - nie musimy mapować całej tablicy

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/types.ts
> +export interface IProduct {
Ten interface jest niepotrzebny - powtarza zadanie klasy `Product` to ona powinna być powiązana z koszykiem

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/types.ts
> +export interface ICart {
Ten `interface` również jest niepotrzebny, powtarza elementy powiązane z `Cart`.

Zauważ że `class` to jednocześnie `typ` + implementacja
Więc samo `class` realizuje zadania `interface` - w tym kontekście przepisywanie tego do `I*` nie jest potrzebne.

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/cart.ts
> +  private products: IProduct[] = [];
Tutaj może być po prostu `products: Product[] = []` (skorzystaj z klasy)

2022-10-08 02:13 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/cart.ts
> +  getAllProducts(): IProduct[] {
tutaj dla bezpieczeństwa można dodać `readonly` wtedy np. razem z klasą:

```typescript
getAllProducts(): readonly Product[] {...}
```

2022-10-13 15:39 UTC, kdrzymalski commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/cart.ts
> +    this.products = this.products.map((product) => {
masz na myśli użycie finda?

2022-10-13 15:44 UTC, kdrzymalski commented
Czy Twoim zdaniem brak użycia generyka jest tutaj problemem? Stwierdziłem że obejdzie się bez niego :D

2022-11-27 14:23 UTC, closed without merging