Solutions/week2/e02 to review
michaljabi/js-na-frontach-zadania pull request #58
Opened 2022-09-28 18:42 UTC by teziovsky

Aby odpalić projekt, należy oczywiście wykonać `npm install`. Następnie w jednej karcie terminala `npm run api`, a w drugiej `npm run dev`. Pod adresem http://localhost:5173 będzie dostępna aplikacja.

2022-09-28 18:43 UTC, teziovsky commented
Przy tworzeniu PR nie mogę Cię @michaljabi dodać jako `Reviewers'a`, ani Cię przypisać 🤔

2022-10-01 05:54 UTC, michaljabi commented
nie szkodzi @teziovsky - widzę te `PR` i sukcesywnie do nich docieram :) Więc nie trzeba mnie dodawać jako Reviewers - faktycznie się nie da, kilka osób już mi to zgłaszało.

2022-10-11 09:03 UTC, michaljabi requested changes
Bardzo podoba mi sie użycie `json-server`
Symulacja zapytań API jest wręcz nie symulacją a faktycznym zapytaniem AJAX.

- super.

Jednak brakuje mi tutaj 2 etapów:
- refaktoryzacji 
- optymalizacji

### Optymalizacja:

Zauważ że Twoja apka po starcie robi `4x` zapytania do:
```javascript
fetch("http://localhost:3001/orders")
```

- co zrobić żeby zapytanie było `1x` skoro to te same dane
- po tym jak dane do nas dotrą - chcemy aby się wyświetliły
- jak spakować to wszystko w jakiś `service` logic ?

### Refactoring:

Po ściągnięciu danych nimi manipulujesz. Jednak zobacz że np. musisz liczyć coś takiego:
```javascript
const totalIncome = orders.reduce((total, order) => total + order.sale, 0);
```

Nie ma w tym nic złego, ale komponent sam to dla siebie przelicza. A co jakbyśmy tego potrzebowali w kolejnym komponencie? Tutaj jest problem ponieważ każdy komponent zliczałby to "po swojemu" od nowa (wzrasta możliwość popełnienia błędu).

jak już będziesz miał miejsce pobierania danych to zadbaj o to żeby:
- w tym samym miejscu przygotować odpowiednie dane potrzebne dla komponentów
- komponenty już pobierały konkretne elementy

Wykorzystaj do tego wiedzę z _Fulent API_ dla `Array` z zadania `w02e01` !

2022-10-11 09:04 UTC, michaljabi commented
Może się okazać że na etapie optymalizacji zapytania już będziesz potrzebował skorzystać np. z 
   - [events](https://www.skypack.dev/view/events) | z bundlerem: [npm events](https://www.npmjs.com/package/events)

2022-10-12 17:08 UTC, teziovsky commented
Okej podszedłem trochę inaczej do zadania. Wyodrębniłem komponenty z plików w katalogu `tiles`.
Dodałem serwis, który zawiera w sobie całą logikę biznesową w kontekście zamówień.
Dodałem przycisk, którym można dodać nowe zamówienie. Po dodaniu zamówienia wszystkie dane się przeliczają 🤔
Co prawda nie skorzystałem w tym przypadku z wzorca `Obserwator` natomiast efekt końcowy wydaje mi się, że jest taki jak być powinien 🤔

2022-12-14 16:46 UTC, michaljabi approved these changes
Super - fajne poprawki. Drobny detal bym jeszcze zmienił w działaniu `orders.service.js`

jednak generalnie rozwiązanie dobrze zoptymalizowane.

2022-12-14 16:46 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/main.js
> +import OrdersService from "./orders/orders.service.js";
to jest singleton. nazwałbym go z małych `ordersService`

Duża litera sugeruje klasę + metody statyczne poniżej. A to nie jest prawda :).

2022-12-14 16:46 UTC, michaljabi commented on week-2-wide-perspective/w02e02-data-manipulation/src/orders/orders.service.js
> +  getTotalOrders(orders) {
Jedyne co bym zmienił to korzystał z `this.orders` zamiast przekazywać je z zewnątrz za każdym razem.

Wiem że zrobiłeś to teraz poprawnie, w sensie - działa dużo lepiej wydajnościowo,
ale jest aż "nazbyt" elastyczne.

Super by było żeby trzymać jednak `orders` za "fasadą" i korzystać tutaj z `this.orders` w tych metodach.
Zawsze możesz, zrobić z tego klasę, w `constructor` podać wtedy bazowe `orders` i na nich działać potem w metodach.

Dlatego zamiast odbierać za każdym razem jako parametr `orders` w każdej z metod. To robiłbym to jednorazowo w jednej metodzie - `getOrders`.

2023-01-08 08:23 UTC, closed without merging