solutions/week1/e03
michaljabi/js-na-frontach-zadania pull request #61
Opened 2022-09-29 11:27 UTC by janossik

2022-10-10 04:12 UTC, michaljabi requested changes
Super.

Widać gdzie są modele danych, jakie są, co obsługuje koszyk.
Wszystko na pierwszy rzut oka.

Brak nadmiarowej logiki i powtórzeń w `interface` + `class`

Jedynie drobne moje sugestie do przeanalizowania @janossik 👍

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/Item.ts
> +export abstract class Item {
Piękny pomysł żeby `Item` było abstrakcyjną bazą modeli danych 👍

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/Item.ts
> +    this.id = Math.round(Math.random() * Math.pow(10, 10)).toString(16);
polecam użycie biblioteki np. `uuid` - wtedy będzie bardziej `pro` :) 

Dodatkowo zauważ że w tym układzie `id` może być `readonly`

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/FreeItem.ts
> +  currency: undefined;
nie wiem czy tutaj nie dałbym `void` jako podkreślenie że tych wartości nie obsługujemy.

W dalszej perspektywie do zasatnowienia się czy Twoja klasa abstakcyjna `Item` nie robi za dużo.
w sensie czy przechowywanie w niej `value` oraz `currency` ma sens.

Zobacz. Naszą "odmienną" klasą jest jedynie `FreeItem` to może warto do `Item` dodać kolejnego abstrakta jako `ValuedItem` (dziedziczącego po `Item`) i on by miał pola `value` + `currency`

Wtedy dziedziczymy po `ValuedItem` w przypadku `AuctionItem` oraz `NowItem`

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/NowItem.ts
> +export class NowItem extends Item {
Zmienił bym nazwę na `BuyNowItem`. ale to szczegół.

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +export class Cart<Product extends Item> {
Tutaj poszedłbym zgodnie z konwencją. Nazwa generyka z dużych:

```typescript
export class Cart<PRODUCT extends Item> { 
//... 
}
```

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +    console.log("Nie znaleziono produktu o podanym id");
Może "mocniej" - zamiast "efektu ubocznego" rzucić wyjątek ?

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +  private producs: Map<string, Product> = new Map();
fajny pomysł, trzymania wpisów jako mapa

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +    return [...this.producs].reduce((acc, [, product]) => acc + product.amount, 0);
Czemu tutaj taka komplikacja zamiast `[...this.products.values()]` ?
Albo lepiej żeby sie nie powtarzać:

`this.getAll().reduce .... `

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +    return [...this.producs.values()];
Pamiętaj że da się też bardziej "implicit" pokazać co robisz:

`Array.from(this.products.values())`

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/controllers/Cart.ts
> +    return [...this.producs].reduce((acc, [, product]) => acc + (product?.value || 0) * product.amount, 0).toFixed(2);
j.w.

2022-10-10 04:12 UTC, michaljabi commented on week-1-ts-ecosystem/w01e03-object-oriented-structure/src/models/NowItem.ts
> +    console.log(`nazwa: ${this.name}, cena: ${this.value}, ilość: ${this.amount}, wartość: ${this.value * this.amount}`);
Ta linia oraz logika zapisu w koszyku:

```
getAmount() {....}
```

sugerują Ci że warto dodać getter do `Item` oznaczający jego wartość jako:
```
get totalValue() {
  return this.value * this.amount
}
```

2022-10-14 13:38 UTC, janossik commented
ValuedItem powodował problemy z koszykiem dla darmowych przedmiotów, poprawna implementacja wymagałaby zaimplementowania dwóch koszyków Cart i CartWithValuedItems

2022-12-14 16:49 UTC, michaljabi approved these changes

2022-12-14 16:49 UTC, closed without merging